import type { Metadata } from "next";
import "./globals.css";
import { NextUILib } from "@/providers/NextUILib";
import { ClerkProvider } from "@clerk/nextjs";
import LayoutProvider from "@/providers/LayoutProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <NextUILib>
            <LayoutProvider>{children}</LayoutProvider>
          </NextUILib>
        </body>
      </html>
    </ClerkProvider>
  );
}
